### ISSUE TITLE
ImportBehaviour.cs

### ISSUE THREAD

**Issue by Niarus** [Seanba/Tiled2Unity#23]
I guess ImportBehaviour.cs should be in the Editor folder rather than Runtime, because it has UnityEditor namespace and while making Unity build it will say that type or namespace name `UnityEditor' could not be found.

Regression from 1.0.0.0.

**Comment by Seanba** [comment]
Thanks for letting me know. I'll take a look at it when I'm back at my home office later today.

Best,
Sean

**Comment by Seanba** [comment]
This has been fixed with version 1.0.0.2 of Tiled2Unity. Thanks again for
alerting me.

**Comment by Niarus** [comment]
Thank you for the fast response. Still don't quite understand why you left this class in Runtime folder. Maybe you want to extend it with ability to import Tiled XML in the runtime or just for an easy update of the current version?

**Comment by Seanba** [comment]
Components that you add to game objects cannot reside in the Editor folder.
I needed a way to track progress of an Tiled2Unity import over time and
decided to go with something that resides in the scene hierarchy (briefly)
for that.

I don't think it's *great* way to go about it but I had difficultly
managing the lifetime of an object without putting it into the scene while
importing. I had made attempts of using a ScriptableObject, and that could
of been an Editor-only thing, but kept running into issues.

**Comment by Niarus** [comment]
Ah, got it. Thank you for clearing up.
